services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  setz:
    image: drsetz/dj_setz:latest
    restart: unless-stopped
    container_name: dj_setz
    ports:
      - "8000:8000"
    depends_on:
      - caddy

  setz_vue:
    image: registry.gitlab.com/setz.de/setz-vue-app/main:latest
    restart: unless-stopped
    container_name: setz_vue
    ports:
      - "8002:80"
    depends_on:
      - caddy

  setz_fastapi:
    image: registry.gitlab.com/setz.de/setz-fastapi/main:latest
    restart: unless-stopped
    env_file:
      - ./fastapi-test.env
    container_name: setz_fastapi
    ports:
      - "8003:8000"
    depends_on:
      - caddy

  setz_php_app:
    image: ghcr.io/thsetz/setz-php:latest
    restart: unless-stopped
    container_name: setz_php_app
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./setz-php/.env:/var/www/html/.env:ro
      - ./setz-php/database:/var/www/html/database
      - ./setz-php/storage/app:/var/www/html/storage/app
      - ./setz-php/storage/logs:/var/www/html/storage/logs
      - ./setz-php/storage/framework:/var/www/html/storage/framework
      - ./setz-php/bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - caddy
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3

  setz_php_nginx:
    image: ghcr.io/thsetz/setz-php:latest
    restart: unless-stopped
    container_name: setz_php_nginx
    user: root
    ports:
      - "8004:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - setz_php_app
      - caddy
    command: ["nginx", "-g", "daemon off;"]

  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=${NEXTCLOUD_APACHE_PORT}
      - NEXTCLOUD_MOUNT=${NEXTCLOUD_MOUNT}
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
