# Docker Compose for Production Deployment
# Usage: docker compose -f docker-compose.production.yml up -d

version: '3.8'

services:
  app:
    image: ghcr.io/thsetz/setz-php:latest
    container_name: setz-php-app
    restart: unless-stopped

    environment:
      # Laravel will read from .env file
      - CONTAINER_ROLE=app

    volumes:
      # Mount .env file (never include in image)
      - ./.env:/var/www/html/.env:ro

      # Persistent storage
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

      # Framework cache (can be ephemeral but persist for performance)
      - storage-framework:/var/www/html/storage/framework
      - bootstrap-cache:/var/www/html/bootstrap/cache

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

  # Nginx web server (if not using Caddy)
  nginx:
    image: nginx:alpine
    container_name: setz-php-nginx
    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public:ro

    depends_on:
      app:
        condition: service_healthy

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  storage-framework:
    driver: local
  bootstrap-cache:
    driver: local

networks:
  app-network:
    driver: bridge
