name: Deploy to Intranet

on:
  workflow_run:
    workflows: ["Build and Push Release Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted
    # Nur deployen wenn Docker Image Build erfolgreich war
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Deploy
        run: |
            deploy.sh

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment successful to Intranet"
          else
            echo "❌ Deployment failed"
            exit 1
          fi
