name: Pint (Fix code style)

on:
  - pull_request

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit linted files
